# fly.toml file generated for mailerapp-python on 2022-08-30T00:31:42-05:00

app = "mailerapp-python"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[mounts]
  destination = "/data"
  source = "mysqldata"

[env]
  FLASK_APP = "app"
  FLASK_DATABASE = "${MYSQL_DATABASE}"
  FLASK_DATABASE_HOST = "${MYSQL_HOST}"
  FLASK_DATABASE_PASSWORD = "${MYSQL_PASSWORD}"
  FLASK_DATABASE_USER = "${MYSQL_USER}"
  MYSQL_DATABASE = "Mailerdb"
  MYSQL_HOST = "MailerHost"
  MYSQL_USER = "Sqluser"
  PORT = "8080"

[build]
 builder = "paketobuildpacks/builder:base"

[experimental]
  cmd = [
    "--default-authentication-plugin", 
    "mysql_native_password", 
    "--datadir", 
    "/data/mysql"
  ]

