# fly.toml file generated for mailerapp-python on 2022-08-30T12:25:32-05:00

app = "mailerapp-python"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  FLASK_APP = "app"
  FLASK_DATABASE = "${MYSQL_DATABASE}"
  FLASK_DATABASE_HOST = "${MYSQL_HOST}"
  FLASK_DATABASE_PASSWORD = "${MYSQL_PASSWORD}"
  FLASK_DATABASE_USER = "${MYSQL_USER}"
  MYSQL_DATABASE = "Mailerdb"
  MYSQL_HOST = "MailerHost"
  MYSQL_USER = "Sqluser"

[experimental]
  cmd = ["--default-authentication-plugin", "mysql_native_password", "--datadir", "/data/mysql"]

[mounts]
  destination = "/data"
  source = "mysqldata"
